# basic Operations in Arrays

In [2]:
import numpy as np
a=np.array([10,20,30,40])
b=np.arange(1,5)

In [3]:
a

array([10, 20, 30, 40])

In [4]:
b

array([1, 2, 3, 4])

In [5]:
a+b

array([11, 22, 33, 44])

In [6]:
a-b

array([ 9, 18, 27, 36])

In [7]:
a*b

array([ 10,  40,  90, 160])

In [8]:
b**2

array([ 1,  4,  9, 16], dtype=int32)

In [9]:
#masking
a>15

array([False,  True,  True,  True])

In [10]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945])

In [11]:
np.sin(b)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Matrix product

-multiplication of matrix is only allowed if number of cloumns in the both matrix are same


In [12]:
A=np.random.randint(0,5,(3,4))
B=np.random.randint(0,5,(4,2))

In [13]:
A

array([[3, 2, 0, 0],
       [3, 3, 3, 0],
       [0, 3, 0, 0]])

In [15]:
B

array([[3, 2],
       [0, 2],
       [4, 3],
       [0, 4]])

In [16]:
np.dot(A,B) #dot is the method which is used to multiple two matrix


array([[ 9, 10],
       [21, 21],
       [ 0,  6]])

In [17]:
c=np.arange(0,24)

In [18]:
c=c.reshape(6,4)

In [19]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
np.sqrt(c)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])

In [22]:
np.sum(c)

276

In [23]:
np.max(c)

23

In [24]:
np.mean(c)

11.5

In [25]:
np.std(c)

6.922186552431729

In [26]:
np.sum(c,axis=0) #sum accross the rows

array([60, 66, 72, 78])

In [ ]:
np.mean(A,axis=1) #