# Broadcasting
- first rule of Numpy : 2 arrays can perform operations only when they have same shape
- broadcasting let two arrays of different shapes to do some operations 
  - a small arrat will repeat itself and convert to the same shape as of another array
  

In [2]:
import numpy as np
A=np.random.randint(0,10,size=(3,3))
a=np.array([[1,2,3]])

In [4]:
A

array([[7, 7, 3],
       [1, 9, 3],
       [2, 7, 8]])

In [5]:
a

array([[1, 2, 3]])

In [6]:
A+a

array([[ 8,  9,  6],
       [ 2, 11,  6],
       [ 3,  9, 11]])

In [7]:
a.T

array([[1],
       [2],
       [3]])

In [9]:
A+a.T

array([[ 8,  8,  4],
       [ 3, 11,  5],
       [ 5, 10, 11]])