# Indexing in Array

In [1]:
import numpy as np
#code below creates a random numpy array between the range of 10 100
np.random.randint(10,100)


35

In [8]:
new_arr=np.random.randint(10,100,(5,4))
#the last third parameter is used for the size 

In [10]:
new_arr

array([[84, 10, 27, 96],
       [39, 81, 88, 92],
       [64, 49, 23, 89],
       [16, 31, 75, 71],
       [56, 80, 46, 49]])

In [11]:
#first row
new_arr[0]

array([84, 10, 27, 96])

In [12]:
#second row
new_arr[-2]

array([16, 31, 75, 71])

In [13]:
#first element
print(new_arr[0,0])

84


In [14]:
#last element
print(new_arr[-1,-1])

49


In [15]:
new_arr.shape

(5, 4)

# Array Slicing

In [17]:
new_arr

array([[84, 10, 27, 96],
       [39, 81, 88, 92],
       [64, 49, 23, 89],
       [16, 31, 75, 71],
       [56, 80, 46, 49]])

In [18]:

'''
synatax of array slicing
arr[start_row_idx:end_row_index+1,start_column_index:end_column index]
'''

'\nsynatax of array slicing\narr[start_row_idx:end_row_index+1,start_column_index:end_column index]\n'

In [20]:
new_arr[2:5,1:4]

array([[49, 23, 89],
       [31, 75, 71],
       [80, 46, 49]])

In [21]:
#third column only
new_arr[:,2]

array([27, 88, 23, 75, 46])

In [22]:
new_arr[0,0]=0

# masking


In [26]:
mask=new_arr>50

In [27]:
np.sum(mask)

10

In [29]:
# to get all values greater than 10
new_arr[mask]

array([96, 81, 88, 92, 64, 89, 75, 71, 56, 80])

In [31]:
new_arr

array([[ 0, 10, 27, 96],
       [39, 81, 88, 92],
       [64, 49, 23, 89],
       [16, 31, 75, 71],
       [56, 80, 46, 49]])

In [32]:
new_arr[2:,2:]=0 

In [33]:
new_arr

array([[ 0, 10, 27, 96],
       [39, 81, 88, 92],
       [64, 49,  0,  0],
       [16, 31,  0,  0],
       [56, 80,  0,  0]])