# Numpy arrays

## array : 
fundamental element in numpy is homogenous array.Numpy array can be 1d 2d 3d ......nd

- Different ways to create np array
    - - 1.np.array()
    - - 2.np.arange

In [3]:
import numpy as np
l=[1,5,8,9]
np_arr=np.array(l)

#numpy array contains same type of elements
#while list can contain multiple types of elements


In [3]:
np_arr

array([1, 5, 8, 9])

In [4]:
type(np_arr)

numpy.ndarray

In [5]:
np_arr.ndim #ndim is used to get dimension of the numpy array

1

In [6]:
np_arr.shape  #important property
#shape basically tells how many elements are there and how they are scattered in the numpy array 


(4,)

In [8]:
print(np_arr)

[1 5 8 9]


### another way of creating numpy array

In [4]:
new_arr=np.arange(3,11,2)

In [5]:
new_arr

array([3, 5, 7, 9])

In [6]:
lst_2d=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
arr_2d=np.array(lst_2d)

In [8]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr_2d.ndim

2

In [11]:
arr_2d.shape

#three rows and three columns

(3, 3)