# Shape Manipulation

In [9]:
import numpy as np
A=np.random.randint(10, 100,(5,4))

In [6]:
A

array([[18, 57, 29, 37],
       [90, 68, 15, 58],
       [89, 69, 21, 97],
       [48, 98, 74, 94],
       [14, 58, 34, 34]])

In [7]:
A.flatten()

#flatten takes all elements and convert the array into one dim

array([18, 57, 29, 37, 90, 68, 15, 58, 89, 69, 21, 97, 48, 98, 74, 94, 14,
       58, 34, 34])

In [11]:
#A.reshape()

In [12]:
A.T #transpose of a matrix

array([[22, 55, 72, 29, 75],
       [35, 14, 14, 53, 25],
       [36, 19, 21, 99, 14],
       [51, 97, 13, 26, 78],
       [35, 83, 13, 71, 45]])

### stacking of arrays- vstack-hstack

In [13]:
a=np.random.randint(0,10,(2,2))
b=np.random.randint(0,10,(2,2))

In [15]:
a

array([[9, 5],
       [5, 4]])

In [16]:
b

array([[8, 1],
       [0, 4]])

In [17]:
np.hstack((a,b))

array([[9, 5, 8, 1],
       [5, 4, 0, 4]])

In [18]:
np.vstack((a,b))

array([[9, 5],
       [5, 4],
       [8, 1],
       [0, 4]])