# Special Arrays in Numpy
- zeros()
- ones()
- diag()
- identity ()


In [3]:

import numpy as np

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.diag([1,2,3])
#used to create a diagonal matrix

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [7]:
np.identity(4) #creates identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])